enum ROUTES {
  // AUTH ROUTE ENTRY POINTS
  AUTH_FORGOT_PASSWORD_SUCCESS = "AUTH_FORGOT_PASSWORD_SUCCESS",
  AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD",
  AUTH_REGISTRATION = "AUTH_REGISTRATION",
  AUTH_LOGIN = "AUTH_LOGIN",
  // MAIN ROUTE ENTRY
  MAIN_HOME = "MAIN_HOME",
  MAIN_FAVOURITES = "MAIN_FAVOURITES",
}

export default ROUTES;
